### ISSUE TITLE
Ajax loaded video, multiple video

### ISSUE THREAD

**Issue by harpreetsb** [lunametrics/youtube-google-analytics#7] opened 2014-10-14 07:54 UTC
does not track ajax loaded video.
So i tried calling trackYouTube(); after ajax call
Now it tracks the ajax loaded video but gives error on video that was already present on page.

event.target.getVideoUrl is not a function.

**Comment by olegafx** [comment] 2015-06-24 14:03
Why did you closed it?

How could I track ajax-loaded videos? `window.onYouTubeIframeAPIReady` fires only once after YouTube API is loaded. Firing it again will cause some troubles (like the one that @harpreetsb pointed)

**Comment by DanWilkerson** [comment] 2015-06-24 20:59
@olegafx You are correct, this should remain open. The issue is when multiple players are bound to the same HTML object. I'd welcome a fix if you want to pull one in, but I won't be addressing this myself.

**Comment by DanWilkerson** [comment] 2016-03-29 17:41
It's possible that we could attach a 'load' listener to the window and sniff for YouTube videos being loaded.

**Comment by DanWilkerson** [comment] 2016-04-05 22:32
There's a fix in now; it requires you to have set the enablejsapi and origin parameters correctly, but if you have, it will bind to the video when it loads in the DOM. It does this by capturing load events and inspecting them. Please test and let me know if you come across any issues.

**Closed as completed by DanWilkerson** 2016-04-05 22:32 UTC
